version: '3.8'

services:
  web:
    build: .
    # run entrypoint.sh first (to set SECRET_KEY), then launch your app
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["python", "main.py"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=car_rental
      - MASTER_PASSWORD=REAPER
      # Optional: pin a SECRET_KEY here
      # - SECRET_KEY=your-hex-32-byte-string
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: car_rental
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/car_rental_db.sql:/docker-entrypoint-initdb.d/car_rental_db.sql

volumes:
  # you can optionally persist mysql data here
  db_data:
    driver: local
